version: 2
jobs:
  build:
    docker:
      - image: golang:1.13
    steps:
      - checkout
      - run: go run github.com/99designs/gqlgen
      - run:
          name: "Enforce Go Formatted Code"
          command: "go fmt ./... 2>&1"
