{
 "title": "HelloWorld",
 "panels": [
  {
   "title": "Request Latency: Create",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "HelloWorld_http_request_duration_seconds{method=\"CREATE\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Custom Logic Latency: beforeCreate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "HelloWorld_custom_logic_duration_seconds{method=\"CREATE\", when=\"before\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Custom Logic Latency: afterCreate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "HelloWorld_custom_logic_duration_seconds{method=\"CREATE\", when=\"after\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Database Latency: Create",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "HelloWorld_database_access_duration_seconds{method=\"CREATE\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  }
 ]
}